name: CI
on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry==1.3.2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: poetry install
      - name: Build
        run: poetry build
      - name: Upload artifact
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        env:
          API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish -u __token__ -p "$API_TOKEN"
